name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Use your desired Java version
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn -Dtest='**/*Test,**/*Tests,**/*TestCase' test -Dsurefire.include="**/*Test.java,**/*Tests.java,**/*TestCase.java" # This runs all tests with the @Test annotation

      - name: Archive Test Results
        if: always()
        run: mvn surefire-report:report-only
