name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the JDK distribution (e.g., temurin, zulu, adopt)

      # Install the latest stable version of Chrome from the mirror
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https curl
          # Download the latest stable version of Chrome from the mirror
          LATEST_CHROME=$(wget -qO- https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/ | grep -oP 'google-chrome-stable_\d+\.\d+\.\d+\.\d+-1_amd64\.deb' | sort -V | tail -n 1)
          wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/$LATEST_CHROME
          sudo dpkg -i $LATEST_CHROME || sudo apt-get install -f -y  # Install Chrome and fix any missing dependencies

      # Install ChromeDriver for the corresponding Chrome version
      - name: Install ChromeDriver
        run: |
          set -x
          # Ensure wget and unzip are installed
          if ! command -v wget &> /dev/null; then
          sudo apt-get install -y wget || true
          fi
          if ! command -v unzip &> /dev/null; then
          sudo apt-get install -y unzip || true
          fi
          
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
          
          # Attempt to fetch ChromeDriver for the Chrome version
          LATEST_DRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION) || { echo "Failed to retrieve ChromeDriver version for major version $MAJOR_VERSION"; exit 1; }
          
          # If failed, fall back to latest ChromeDriver
          if [ -z "$LATEST_DRIVER" ]; then
          echo "Fetching latest ChromeDriver version"
          LATEST_DRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE) || { echo "Failed to retrieve the latest ChromeDriver version"; exit 1; }
          fi
          
          # Download and set up ChromeDriver
          wget https://chromedriver.storage.googleapis.com/$LATEST_DRIVER/chromedriver_linux64.zip || { echo "Failed to download ChromeDriver"; exit 1; }
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          set +x

      - name: Run tests
        run: |
          mvn clean install
