name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Latest version

      - name: Set up Java
        uses: actions/setup-java@v3  # Ensure you are using v3
        with:
          java-version: '11'           # Specify your desired Java version
          distribution: 'temurin'      # Specify the JDK distribution

      - name: Cache dependencies
        uses: actions/cache@v3  # Ensure you are using v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install  # Your build command
