name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the JDK distribution (e.g., temurin, zulu, adopt)

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Install ChromeDriver (Check for wget/unzip and fix the ChromeDriver version installation)
      - name: Install ChromeDriver
        run: |
          # Ensure wget and unzip are installed, ignore errors if they are already installed
          if ! command -v wget &> /dev/null; then
          sudo apt-get install -y wget || true
          fi
          if ! command -v unzip &> /dev/null; then
          sudo apt-get install -y unzip || true
          fi
          
          # Get Chrome and ChromeDriver version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
          LATEST_DRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION)
          
          # Download and set up ChromeDriver
          wget https://chromedriver.storage.googleapis.com/$LATEST_DRIVER/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests
        run: |
          ./gradlew test # or your build tool command here
