name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Verify Java and Maven
        run: |
          java -version
          mvn -v

      - name: Build
        run: mvn clean install

      - name: Upload Surefire test reports  # Add this step
        if: failure()
        uses: actions/upload-artifact@v4.0.0
        with:
          name: surefire-reports
          path: target/surefire-re
